### ISSUE TITLE
Question: SP Mobile App

### ISSUE THREAD

**Issue by kmartindale** [bcameron1231/SharePoint-Framework#3]
Does this solution also work in the SP Mobile App? Trying to figure out if the navigation present in the mobile application is native or pulling from the web?

**Comment by bcameron1231** [comment]
it does not replace the mobile app hamburger menu. Nor did I add any styles/css for mobile. This repository was merely a starting place for others to work through these customizations.

**Comment by kmartindale** [comment]
Thanks so much. I'm trying to figure out if that is even possible or if I'm going to end up swinging and missing on manipulating the hubsite nav to support security trimming. (any guidance welcome, but i appreciate the quick response)
