### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by kruegernet** [bcameron1231/SharePoint-Framework#4]
Hi Beau.

Do you know if the react-hubsite-securitytrim-navbar should still work with current SPO tech?

I'm able to get it to work with localhost CDN but when I build/deploy to the app catalog, I cannot deploy from there to a hub site collection.

I can successfully install the app to individual sharepoint sites, but I do not see the menu. Are there additional steps to activate the UI?

Thanks!!!

**Comment by bcameron1231** [comment]
Hi! Should still work. After you install the app, are you adding it to a UserCustom action in order for it to show up? Installing the app on a site, doesn't make it automatically show up. You need to attach the App to a Custom Action.

I usually do this via PowerShell Add-PnPCustomAction. There is a sample in the [documentation](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpcustomaction?view=sharepoint-ps).

**Comment by kruegernet** [comment]
I am not, that is probably why it doesn't work for me! I will try now.

Perhaps that would be good info for the readme.md? I wonder if there are other folks finding their way to your project like me who aren't as familiar with SharePoint in general. Thanks for the prompt reply! Very unexpected

**Comment by kruegernet** [comment]
OK, attached to action and working. Thanks!! If you'd like any additional verbiage for your readme let me know and I'll be happy to provide.

**Comment by bcameron1231** [comment]
If you'd like to provide some additional verbiage, that would be great! i'll merge the PR whenever you send it in! :)
